subjects: ["cs.AI", "cs.CL", "cs.LG"]
keywords:
  [
    "language model",
    "gpt",
    "llm",
    "long context",
    "lora",
    "hallucination",
    "prompt",
    "code",
    "chat",
    "retrieval augmented generation",
    "retrieval-augmented generation",
    "rag",
    "multi-run",
    "chain-of-thought",
    "tree-of-thought",
    "agent",
  ]
translate: true
