subjects: ["cs.CV", "cs.CL", "cs.CR", "cs.LG"]
keywords:
  [
    "secure",
    "security",
    "privacy",
    "protect",
    "defense",
    "attack",
    "robust",
    "biometric",
    "steal",
    "extraction",
    "membership infer",
    "federate",
    "fair",
    "interpretability",
    "explainability",
    "watermark",
    "diffusion",
    "noise learning",
    "data-free",
    "transformer",
    "generative",
    "large language model",
    "segmentation",
  ]
translate: false
