name: Get Arxiv Papers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests PyYAML

      - name: run script
        run: |
          git pull
          python main.py
      
      - name: push markdown file
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "update"
          git push --force origin main

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'static.yml',
              ref: 'main',
            })
